### ISSUE TITLE
Advantages over the "official" GRPC gem

### ISSUE THREAD

**Issue by TheRusskiy** [cookpad/grpc_kit#25]
Not really an issue, but it would be nice to know what are the advantages of using this gem over the "official" one.

**Comment by ganmacs** [comment]
When I developed this gem, the official grpc gem didn't have the following feature(I'm not sure the current status). grpc_kit(and [griffin](https://github.com/cookpad/griffin)) supports them.

* Multi threads but multi-process
  * [griffin](https://github.com/cookpad/griffin) which uses grpc_kit internally runs in multi-process.
  * This is the biggest motivation I developed this gem(and griffin)

* Interceptors has a bug
  * https://github.com/grpc/grpc/pull/15801

* Interceptors can't get the status code
  * https://github.com/grpc/grpc/pull/15733

* Response status as Trailers-Only if initial metadata has not been sent
  * https://github.com/grpc/grpc/pull/16490

**Comment by TheRusskiy** [comment]
@ganmacs thank you!
A few more questions if you don't mind 😄
I am interested in flow control.
How does grpc_kit deal with incoming requests? The current version of grpc gem has a specified number of threads (https://github.com/grpc/grpc/blob/a85b78baa69a57b724d6cfe35a1dadb9719f2c56/src/ruby/lib/grpc/generic/rpc_server.rb#L163), where each thread accepts a request. If there are more requests than threads it raises `RESOURCE_EXHAUSTED`. This is not very desirable (IMHO), since during an influx of requests you end up dropping them really quickly, or you need to have too many threads, but then you may not be prepared to handle 1000 threads in parallel at the same time.
After a few minutes of glancing at grpc_kit code I don't see an upper bound for a number of requests in a queue:
https://github.com/cookpad/grpc_kit/blob/master/lib/grpc_kit/rpc_dispatcher.rb#L43
So probably it's gonna end up queueing requests until it runs out of memory? Or am I missing something?
What's your opinion on this matter?
Maybe we are going to end up having some documentation about it 📜

**Comment by ganmacs** [comment]
> So probably it's gonna end up queueing requests until it runs out of memory?

You're right.
I haven't seen such a situation when using griffin in prod. but It might be better to add an option which is like listen(2)'s backlog to grpc_kit and if the queue size gets over it, it returns `RESOURCE_EXHAUSTED`.

**Comment by TheRusskiy** [comment]
@ganmacs thank you for the reply again.
Gonna close this issue.
